config/routes.rb
Everoam2::Application.routes.draw do
  get "profiles/show"
  resources :roams
  post 'roams/image', to: 'roams#create_image', as: :roams_image
  delete 'roams/image/:id', to: 'roams#destroy_image'

  devise_for :users

  devise_scope :user do
    get 'join', to: 'devise/registrations#new'

    get 'login', to: 'devise/sessions#new'

    get 'settings', to: 'devise/registrations#edit'
  end

root "roams#index"

  get 'policies', to: 'pages#policies'

  get 'about', to: 'pages#about'

  get 'help', to: 'pages#help'

  get 'terminate', to: 'pages#terminate'

  get 'discover', to: 'pages#discover'

  get '/:id', to: 'profiles#show'

end

app/models/roam.rb
class Roam < ActiveRecord::Base
	belongs_to :user

	has_many :images, class_name: 'RoamImage', dependent: :destroy
	accepts_nested_attributes_for :images, :allow_destroy => true

 	 default_scope -> { order('created_at DESC') }
  	validates :user_id, presence: true

	has_attached_file :image, :styles => { :large => "800x600>", :medium => "300x300>", :thumb => "100x100>" }


	validates :title, presence: true





end

app/models/roam_image.rb
class RoamImage < ActiveRecord::Base
  belongs_to :roam

  validates :sequence_num, numericality: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  validates :name, presence: true

  validates :username, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9]+\Z/ }
  before_save { |user| user.username = user.username.downcase }







        has_many :roams, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected




 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :username
   devise_parameter_sanitizer.for(:account_update) << :username
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
   devise_parameter_sanitizer.for(:account_update) << :location
   devise_parameter_sanitizer.for(:account_update) << :bio




 end
end

app/controllers/concerns/s3_presigned_post.rb
module S3PresignedPost
  def s3_presigned_post(path = '')
    key = "#{Rails.env}/#{path}/#{SecureRandom.uuid}_${filename}"
    bucket = AWS::S3.new.buckets['everoam']
    presigned_post = bucket.presigned_post(key: key, success_action_status: 201, acl: :public_read)

    { url: presigned_post.url.to_s, fields: presigned_post.fields }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show



	@user = User.find_by_username(params[:id])
	if @user
		@roams = @user.roams.all
		render action: :show
	else

  	render file: 'public/404', status: 404, formats: [:html]
  	end


  end
end

app/controllers/roams_controller.rb
class RoamsController < ApplicationController
  before_action :set_roam, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]









  include S3PresignedPost

  def index
    @roams = Roam.all.paginate(:page => params[:page], :per_page => 12)

  end

  def show
  end

  def new
    @roam = current_user.roams.build
    @roam.images.build
    @s3_presigned_posts = (1..300).map { |i| s3_presigned_post('roams') }
  end

  def edit
    @s3_presigned_posts = (1..300).map { |i| s3_presigned_post('roams') }
  end

  def create
    @roam = current_user.roams.build(roam_params)
    if @roam.save
      redirect_to @roam
    else
      render action: 'new'
    end
  end

  def update
    if @roam.update(roam_params)
      redirect_to @roam
    else
      render action: 'edit'
    end
  end

  def destroy
    @roam.destroy
    redirect_to roams_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roam
      @roam = Roam.find(params[:id])
    end

    def correct_user
      @roam = current_user.roams.find_by(id: params[:id])
      redirect_to roams_path if @roam.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roam_params
      params.require(:roam).permit(:title, :location, images_attributes: [:id, :image_large_url, :image_medium_url, :image_thumb_url, :caption, :sequence_num, :_destroy] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/roams_helper.rb
module RoamsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <ul>
    <li class="footies"><%= link_to "about", about_path %></li>
    <li class="footies"><a href="http://blog.everoam.com">blog</a></li>
    <li class="footies"><%= link_to "policies", policies_path %></li>
    <li class="footies"><%= link_to "help", help_path %></li>
  </ul>


</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">


<div class="eighty_percent minn">


    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

      </button>

    <%= link_to root_path, class: "brand" do %>
       <div class="logo">Everoam</div>
       <div id="betatag">beta</div>
       <% end %>



    </div>




    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">



      <ul class="nav navbar-nav navbar-right">




         <% if user_signed_in? %>



           <ul class="nav navbar-nav navbar-right">


        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%=current_user.username%>
            <b class="caret"></b></a>
          <ul class="dropdown-menu">


          <li class="center"><%= link_to 'new', new_roam_path %></li>

            <li class="center"><%= link_to "profile", "#{root_url}#{current_user.username}" %>

            </li>



           <li class="center"><%= link_to "settings", settings_path %></li>
            <li class="divider"></li>

            <li class="center"><%= link_to "log out", destroy_user_session_path, method: :delete %></li>

          </ul>
        </li>
      </ul>

         <% else %>

         <li><%= link_to "Login", login_path %></li>

         <li><%= link_to "Join",  join_path %></li>




         <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <div class="tiptop">
    everoam
  </div>
  <title>Everoam</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel = "shortcut icon" href=".\favicon.ico">
</head>

<body>

 <%= render 'layouts/header' %>

<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
<%= yield %>
</body>
</html>

app/views/pages/_home.html.erb
<div id="banner">


	<% if user_signed_in? %>

	Welcome back, <%=current_user.name%>


	<% else %>

	A Place to Share Your Adventures, Big or Small

	<% end %>


</div>

<% if user_signed_in? %>


<% else %>
<body class="home_image">

<div class="registrations">
<div class="panel-body">
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
	<%= devise_error_messages! %>
<div class="form-group">
	<%= f.text_field :name, class: "form-control", :autofocus => true, placeholder: "Full Name" %>
</div>
	<div class="form-group">
	<%= f.text_field :username, class: "form-control", :autofocus => true, placeholder:"Username" %></div>
	<div class="form-group">
	<%= f.email_field :email, class: "form-control", :autofocus => true, placeholder:"Email" %></div>
	<div class="form-group">
	<%= f.password_field :password, class: "form-control", placeholder:"Password" %>
	</div>
	<%= f.submit "Sign up", class: "btn btn-primary" %>
<% end %>
<span class="twelve">by signing up, you agree to our <%= link_to "policies", policies_path %></span>

</div>
</div>



</body>
<%= render 'layouts/footer' %>
<% end %>

app/views/pages/about.html.erb
<div class="container">
	<div class="others_top">

		<div class="pages_nav"><%= link_to "help", help_path %></div>
		<div class="pages_nav"><%= link_to "policies", policies_path %></div>

		<div class="pages_nav"><a href="http://blog.everoam.com">blog</a></div>









	</div>
<div class="top_word">
	About
</div>
<hr>

<div class="pages_text">

	Everoam is a place to share your adventures, experiences, and essentially...your roams!
	No roam is too big or small. We are developing a simple and easy way to share these
	experiences with your friends, family, and the internet!

	<hr>
	<p>Everyone on the team enjoys discovery and exploration. Almost as much as we love
	going out and experiencing, we love to see others discover and enjoy new things. That said, you will also
be seeing lots of roams from us here at Everoam! </p>
	<p>We are a small team based in New York and the Midwest and are available to
	 <a href="mailto:hello@everoam.com">contact</a> if you just want to say hi or anything else!</p>

	<hr>
	<h5 class="overh">FOUNDED</h5>
	<p class="underh">October 2014</p>
	<h5 class="overh">FOUNDER & CEO</h5>
	<p class="underh">Alex Beer</p>
	<h5 class="overh">EMAIL</h5>
	<p class="underh"><a href="mailto:hello@everoam.com">hello@everoam.com</a></p>
</div>

</div>

app/views/pages/comingsoon.html.erb
<body class="coming_soon">


<div class="sooncenter">

<div id="sooneveroam">EVEROAM <span class="aplace">a place to share adventures</span>

  <p>COMING SOON <span class="aplace"><a href="mailto:hello@everoam.com">contact us</a></span></p></div>


<div class="bison"></div>
<div class="bison"></div>
<div class="bison"></div>
<div class="bison"></div>
<div class="bison"></div>
<div class="bison"></div>


</div>


</body>

app/views/pages/help.html.erb
<div class="container">
	<div class="others_top">
		<div class="pages_nav"><%= link_to "about", about_path %></div>
		<div class="pages_nav"><%= link_to "policies", policies_path %></div>

		<div class="pages_nav"><a href="http://blog.everoam.com">blog</a></div>

	</div>
	<div class="top_word">
		Help
	</div>
<hr>
	<div class="pages_text">

		<span class="q">How do I contact Everoam?</span>
		<p>You can email us at <a href="mailto:hello@everoam.com">hello@everoam.com</a></p>
		<span class="q">So...What is a roam?</span>
		<p>A roam is an experience, an adventure, or anything else that you believe can be storybooked!</p>
		<span class="q">Can I follow other people or like posts?</span>
		<p>Currently, those are not features. We are working on expanding and are finding new
		and exciting things for you to do. Updates will be common to make the site as awesome as
		we can get it.</p>
		<span class="q">Are there any tips for making a "good" roam?</span>
		<p> A roam is what you make of it! But...We can recommend a few things.
				<ul class="tips">
						<li>Use the best camera you have for taking the photographs</li>
						<li>Provide concise descriptions/captions</li>
						<li>Try to tell a story</li>
						<li>Make sure to share it with your friends!</li>
				</ul>
		<span class="q"> What if I want to upload more than 10 photos or captions?</span>
		<p> Currently, that is the limit. For longer, we would recommend having a
		part 1 and part 2 for your roam. </p>
		<span class="q"> Who makes Everoam?</span>
		<p> You can read about us and the site <%= link_to "here", about_path %></p>
		<span class="q"> When will Everoam be out of Beta?</span>
		<p> There is no set date yet but we are working hard! </p>
	</div>
</div>

app/views/pages/home.html.erb
<body class="home_image">



<div id="banner">


	<% if user_signed_in? %>

	Welcome back, <%=current_user.name%>

	<% else %>

	A Place to Share Your Adventures, Big or Small

	<% end %>


</div>

<% if user_signed_in? %>

<div id="loggedinhome">
	<div class="loghomenavs">
		<%= link_to "#{root_url}#{current_user.username}" do %>
		<span class="glyphicon glyphicon-user"></span>
		<% end %>
	</div>
	<div class="loghomenavs">
		<%= link_to new_roam_path do%>
		<span class="glyphicon glyphicon-pencil"></span>
		<% end %>
	</div>
</div>

<% else %>


<div class="registrations">

<div class="panel-body">

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
	<%= devise_error_messages! %>



<div class="form-group">

	<%= f.text_field :name, class: "form-control", :autofocus => true, placeholder: "Full Name" %>
</div>

	<div class="form-group">

	<%= f.text_field :username, class: "form-control", :autofocus => true, placeholder:"Username" %></div>


	<div class="form-group">

	<%= f.email_field :email, class: "form-control", :autofocus => true, placeholder:"Email" %></div>

	<div class="form-group">

	<%= f.password_field :password, class: "form-control", placeholder:"Password" %>
	</div>



	<%= f.submit "Sign up", class: "btn btn-primary" %>
<% end %>


<span class="twelve">by signing up, you agree to our <%= link_to "policies", policies_path %></span>
<% end %>

</div>






</div>

</body>
<%= render 'layouts/footer' %>

app/views/pages/policies.html.erb
<div class="container">
	<div class="others_top">
		<div class="pages_nav"><%= link_to "about", about_path %></div>
		<div class="pages_nav"><%= link_to "help", help_path %></div>


		<div class="pages_nav"><a href="http://blog.everoam.com">blog</a></div>

	</div>
	<div class="top_word">
		Policies
	</div>
	<hr>
<div class="pages_text">

	<div class="terms">
		<p>
			PLEASE READ THESE TERMS OF USE BEFORE SIGNING UP AND PARTICIPATING IN
			EVEROAM.COM. THESE TERMS OUTLINE THE AGREEMENT BETWEEN THE WEBSITE AND
			THE USER. IT IS TO PROVIDE BOTH PARTIES WITH SAFETY WHILE USING THE
			SERVICES OFFERED BY EVEROAM.COM AND ANY ASSOCIATED WEBSITES. IF YOU
			ARE WILLING TO ENTER THE EVEROAM/USER AGREEMENT, THEN AND ONLY THEN, MAY
			YOU SIGN UP.
		</p>
		<p>
			The services that are offered through everoam.com are provided as is and does
			not contain any sort of warranty or protection. We reserve the right to
			discontinue any post, account, feature, or service all together with
			or without reason at our sole discretion.
		</p>
		<p>Since this is a site for all ages, you may not post any images or written text of
		an inappropriate nature. These posts will be removed immediately. Inappropriate posts
		contain, but are not limited to, images of sexual nature, gore, and illegal
		substances or actions. Please use common sense. </p>
		<p>Try to post only original images but if not,
			any image that is not your own must contain a citation or link from where it came.</p>
		<p>
			We reserve the right to modify any terms and conditions at any time
			for any reason, with or without notification to the users.
		</p>
		<p>
			We do not provide any security for theft of images or anything else that you put on the website,
			everoam.com.
		</p>


		<p>We will not share any of your personal information or send you any unrequested emails.</p>
		<p>we are not responsible for any hacking or other illegal activity that may compromise our database. If
		this is to happen, legal action will be taken</p>
		<hr>
		<p> For any questions, please email us at <a href="mailto:hello@everoam.com">hello@everoam.com</a></p>
	</div>
</div>
</div>

app/views/pages/terminate.html.erb
<body class="terminate">


<h1 class="unhappy">Unhappy?</h1>
<div class="center">
<p><%= button_to "Delete My Account", registration_path(resource_name),
:data =>  { :confirm => "Are you sure?" }, :method => :delete , class: "terminating" %></p>
</div>
<h1 class="unhappy">We Will Miss You</h1>

</body>

app/views/profiles/show.html.erb
<div class="eighty_percent minn">

<div class="page-header">

	<p class="join"><%= @user.name %>
	<span class="prof_location"> <%= @user.location %> </span></p>
	<p class="prof_bio"><%= @user.bio %></p>
</div>

</div>

<div class="contain_width">

<div id="roams" class="transitions-enabled">
<% if @roams %>
	<% @roams.each do |roam| %>

		<div class="box">
			<%= link_to image_tag(roam.images.first.try(:image_medium_url)), roam %>
		<div class="right panel-body">
        <div class="roamtitle"><%= roam.title %></div>

        <div id="line"></div>



                <div class="float_left timeago">
        <%=time_ago_in_words(roam.created_at) %> ago
                </div>


        <% if roam.user == current_user %>
				<div class="glyphsline ">
       <div class="float_right minenavs">
        <%= link_to edit_roam_path(roam) do %>
        <span class="glyphicon glyphicon-edit"></span>
        <% end %>
      	<span class="gray"> / </span>
        <%= link_to roam, method: :delete, data: { confirm: 'Are you sure you want to delete this Roam?' } do %>
        <span class="glyphicon glyphicon-remove"></span>
        <% end %>
      </div>
		</div>


      <% end %>
  </div>
</div>







	<% end %>
	<% end %>
	</div>
</div>
</div>

app/views/roams/_form.html.erb
<%= form_for(@roam, html: { class: 'roam' }) do |f| %>
  <% if @roam.errors.any? %>
    <div id="error_explanation">
      <h2>Hold Up!</h2>
        <ul>
            <% @roam.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
      </ul>
    </div>
  <% end %>

<br>

<div class="title">
  <div class="form-group" >
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
</div>
<div class="location">
    <div class="form-group">
      <%= f.text_field :location, class: "form-control", placeholder: "Location" %>
    </div>
  </div>

<script type="text/javascript">
  s3PresignedPosts = <%= @s3_presigned_posts.to_json.html_safe %>;
</script>

<%= f.fields_for :images do |ff| %>
  <div class="images-fields">
    <% unless ff.object.image_thumb_url.blank? %>
      <%= image_tag ff.object.image_thumb_url %>
    <% end %>
    <%= file_field_tag 'image', class: 'custom-file-input' %>
    <%= ff.hidden_field :image_large_url %>
    <%= ff.hidden_field :image_medium_url %>
    <%= ff.hidden_field :image_thumb_url %>
    <%= ff.hidden_field :sequence_num, 'class' => 'sequence' %>
    <br>
    <%= ff.text_field :caption, class: 'form-control', placeholder: 'Caption' %>
    <br>



    <div class="progress" style="display: none">
      <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
      </div>
    </div>
  </div>
<% end %>

<button type="button" class="roundbutton" id="add_image_fields">
  <div class="plus">+</div>
</button>


<br>
<br>

<% f.submit %>

<!-- Button trigger modal -->
<button class="btn btn-primary">
  Create Roam
</button>
<br>



  </div>
</div>


 <% end %>


</div>

app/views/roams/edit.html.erb
<div class="container">
  <p></p>
<p class="join">Editing</p>

<%= render 'form' %>

<br>
<br>
</div>

app/views/roams/index.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55856823-1', 'auto');
  ga('send', 'pageview');

</script>




<% if user_signed_in? %>


<div class="eighty_percent minn">
    <div class="index_top_word">
      Explore and Discover
    </div>



  <% if user_signed_in? %>
      <%= link_to 'New Roam', new_roam_path, class: "btn btn-new_roam" %>
  <%end%>

  <div id="line1"></div>
</div>
<br>
<div class="contain_width">
<div id="roams" class="transitions-enabled">
    <% @roams.each do |roam| %>
      <div class="box">
        <%= link_to image_tag(roam.images.first.try(:image_medium_url)), roam %>
        <div class="right panel-body">
        <div class="roamtitle"><%= roam.title %></div>


        <div id="line"></div>
        <b>
        <%= link_to roam.user.username, roam.user.username if roam.user %>
      </b>

<div class="float_right timeago">
      <%= time_ago_in_words(roam.created_at) %> ago

</div>


<% if current_user && roam.user == current_user %>
<br>
<div class="glyphsline">
<div class="float_right minenavs">
    <%= link_to edit_roam_path(roam) do%>
     <span class="glyphicon glyphicon-edit"></span>
     <% end %>
     <span class="gray">   /  </span>
    <%= link_to roam, method: :delete, data: { confirm: 'Are you sure you want to delete this Roam?' } do %>
    <span class="glyphicon glyphicon-remove"></span>
    <% end %>
</div>
</div>
<% end %>



    </div>
  </div>
    <% end %>
  </div>

  <%= will_paginate @posts %>

</div>



<br>
<br>
</div>
<% else %>


<body class="home_image">

  <div id="banner">


<div class="jumbotron">

    A Place to Share Your Adventures, Big or Small
</div>


  </div>

<div class="registrations">
<div class="panel-body">
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>
<div class="form-group">
  <%= f.text_field :name, class: "form-control", :autofocus => true, placeholder: "Full Name" %>
</div>
  <div class="form-group">
  <%= f.text_field :username, class: "form-control", :autofocus => true, placeholder:"Username" %></div>
  <div class="form-group">
  <%= f.email_field :email, class: "form-control", :autofocus => true, placeholder:"Email" %></div>
  <div class="form-group">
  <%= f.password_field :password, class: "form-control", placeholder:"Password" %>
  </div>
  <%= f.submit "Sign up", class: "btn btn-primary" %>
<% end %>
<span class="twelve">by signing up, you agree to our <%= link_to "policies", policies_path %></span>

</div>
</div>


</body>
<%= render 'layouts/footer' %>

<% end %>

app/views/roams/new.html.erb
<div class="container">
<%= render 'form' %>
</div>
<div class="bottom_of_page">
</div>

app/views/roams/show.html.erb
<div class="roam_show">

<p id="notice"></p>

<div class="text-center">
<br>
<h4 class="title_on_show"><%= @roam.title %></h4>


<p><%=@roam.location %></p>

<br>

<% @roam.images.order(sequence_num: :asc).each do |image| %>
  <%= image_tag image.image_large_url %>
  <br><br>
  <div class="caption_contain">
    <p><%= image.caption %></p>
  </div>
  <br/>
<% end %>

</div>

<hr>


<div class="float_left">
<div class="user_and_edit">
<%= link_to @roam.user.username, "#{root_url}#{@roam.user.username}" if @roam.user %>


<% if @roam.user == current_user %>
	| <%= link_to 'edit', edit_roam_path(@roam) %>
<% end %>
</div>
</div>
<br>
<hr>
</div>